/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        vsc: {
          bg: 'var(--vsc-bg)',
          fg: 'var(--vsc-fg)',
          'sidebar-bg': 'var(--vsc-sidebar-bg)',
          'sidebar-fg': 'var(--vsc-sidebar-fg)',
          'input-bg': 'var(--vsc-input-bg)',
          'input-fg': 'var(--vsc-input-fg)',
          'input-border': 'var(--vsc-input-border)',
          'input-placeholder': 'var(--vsc-input-placeholder)',
          'btn-bg': 'var(--vsc-btn-bg)',
          'btn-fg': 'var(--vsc-btn-fg)',
          'btn-hover': 'var(--vsc-btn-hover)',
          'btn-sec-bg': 'var(--vsc-btn-sec-bg)',
          'btn-sec-fg': 'var(--vsc-btn-sec-fg)',
          'btn-sec-hover': 'var(--vsc-btn-sec-hover)',
          border: 'var(--vsc-border)',
          'tab-active': 'var(--vsc-tab-active)',
          'tab-inactive': 'var(--vsc-tab-inactive)',
          'list-hover': 'var(--vsc-list-hover)',
          'list-active': 'var(--vsc-list-active)',
          'list-active-fg': 'var(--vsc-list-active-fg)',
          focus: 'var(--vsc-focus)',
          'badge-bg': 'var(--vsc-badge-bg)',
          'badge-fg': 'var(--vsc-badge-fg)',
          'dropdown-bg': 'var(--vsc-dropdown-bg)',
          'dropdown-fg': 'var(--vsc-dropdown-fg)',
          'dropdown-border': 'var(--vsc-dropdown-border)',
          'widget-bg': 'var(--vsc-widget-bg)',
          'widget-fg': 'var(--vsc-widget-fg)',
          'widget-border': 'var(--vsc-widget-border)',
          'sash-hover': 'var(--vsc-sash-hover)',
          'notify-bg': 'var(--vsc-notify-bg)',
          'notify-fg': 'var(--vsc-notify-fg)',
          'notify-border': 'var(--vsc-notify-border)',
          success: 'var(--vsc-success)',
          warning: 'var(--vsc-warning)',
          error: 'var(--vsc-error)',
          info: 'var(--vsc-info)',
          link: 'var(--vsc-link)',
          shadow: 'var(--vsc-shadow)',
          desc: 'var(--vsc-desc)',
        },
      },
      boxShadow: {
        vsc: '0 2px 8px var(--vsc-shadow)',
      },
      keyframes: {
        'slide-in': {
          from: { transform: 'translateX(100%)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        pulse: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.15' },
        },
      },
      animation: {
        'slide-in': 'slide-in 200ms ease-out',
        'fade-out': 'fade-out 300ms ease-in forwards',
        'skeleton': 'pulse 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
